DEFAULT_CRITICAL_SUCCESS_RANGE = (3, 4)
DEFAULT_CRITICAL_FAIL_RANGE = (17, 18)

MAX_SUCCESS_CRITICAL_VALUE = 6
MIN_FAIL_CRITICAL_VALUE = 15

RESULT_SUCCESS = 'Success!'
RESULT_CRITICAL_SUCCESS = 'Critical success!!!'
RESULT_FAIL = 'Fail.'
RESULT_CRITICAL_FAIL = 'Critical fail...'
