version: '3.7'

services:

  tarkir-db:
    image: library/postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    image: fadich95/tarkir-tools:prod
    restart: unless-stopped
    depends_on:
      - tarkir-db
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./tarkir-upload/:/tarkir-tools/static/upload

  app:
    image: fadich95/tarkir-spells:prod
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5001:80
