version: '3.7'


x-db-env-variables: &db-env-variables
  TR_DB_USERNAME: 'postgres'
  TR_DB_PASSWORD: 'my_secret_password'
  TR_DB_PORT: 5434


x-api-env-variables: &api-env-variables
  TR_DB_HOST: 'db'


services:

  tarkir-db:
    image: library/postgres:13
    container_name: tarkir-db
    ports:
      - 5434:5432
    environment:
      <<: *db-env-variables
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql  # TODO: check this
      
#  migration:
#    build: .
#    container_name: migration
#    command: 'alembic upgrade head'
#    depends_on:
#      - tarkir-db
#    environment:
#      <<: *db-env-variables
#      <<: *api-env-variables
#    volumes:
#      - .:/tarkir-tools

  api:
    build: .
    container_name: api
    command: 'python -m api'
    ports:
    - 5000:5000
    depends_on:
      - tarkir-db
    environment:
      <<: *db-env-variables
      <<: *api-env-variables
      TR_API_SERVER_PORT: 5000
    volumes:
      - .:/tarkir-tools

  admin:
    build: .
    container_name: admin
    command: 'python -m admin'
    ports:
      - 4999:4999
    depends_on:
      - tarkir-db
    environment:
      <<: *db-env-variables
      <<: *api-env-variables
      TR_API_SERVER_PORT: 4999
      SANIC_ADMIN_USER: 'admin'
      SANIC_ADMIN_PASSWORD: '123456'
    volumes:
      - .:/tarkir-tools
