version: '3.7'

services:

  db:
    image: library/postgres:13
    container_name: db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'my_secret_password'
