"""Added image fields

Revision ID: 1f7aee558ff2
Revises: 504843d6b728
Create Date: 2021-12-05 15:15:07.527435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7aee558ff2'
down_revision = '504843d6b728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('image', sa.String(length=1024), nullable=True))
    op.add_column('spell', sa.Column('image', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spell', 'image')
    op.drop_column('school', 'image')
    # ### end Alembic commands ###
