"""Removed bonus fields from School model

Revision ID: 2482f0618219
Revises: acb4e10d3cd5
Create Date: 2021-12-01 15:24:30.038805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2482f0618219'
down_revision = 'acb4e10d3cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'cycle_bonus_three')
    op.drop_column('school', 'cycle_bonus_two')
    op.drop_column('school', 'cycle_bonus_one')
    op.drop_column('school', 'cycle_bonus_zero')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('cycle_bonus_zero', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('school', sa.Column('cycle_bonus_one', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('school', sa.Column('cycle_bonus_two', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('school', sa.Column('cycle_bonus_three', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
