"""Effect models added

Revision ID: 3f8675dd9578
Revises: 48fa562c06d6
Create Date: 2021-12-24 11:27:36.699945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8675dd9578'
down_revision = '48fa562c06d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_to_create', sa.String(length=1024), nullable=True),
    sa.Column('cost', sa.String(length=1024), nullable=True),
    sa.Column('duration', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('effect_to_color',
    sa.Column('effect_id', sa.Integer(), nullable=False, on_delete='CASCADE'),
    sa.Column('color_id', sa.Integer(), nullable=False, on_delete='CASCADE'),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['effect_id'], ['effect.id'], ),
    sa.PrimaryKeyConstraint('effect_id', 'color_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('effect_to_color')
    op.drop_table('effect')
    # ### end Alembic commands ###
