"""Removed cost and time_to_create from effect

Revision ID: f660ba3a518b
Revises: 3f8675dd9578
Create Date: 2021-12-24 14:31:01.043011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f660ba3a518b'
down_revision = '3f8675dd9578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('effect', 'time_to_create')
    op.drop_column('effect', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('effect', sa.Column('cost', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('effect', sa.Column('time_to_create', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
