"""Initial migration

Revision ID: 0e4ff34036d3
Revises: 
Create Date: 2020-11-02 21:26:34.278997

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '0e4ff34036d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('shortcut', sa.String(length=1), nullable=False),
    sa.Column('hex_code', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('shortcut')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('shortcut', sa.String(length=2), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('shortcut')
    )
    # ### end Alembic commands ###

    insert_colors()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    op.drop_table('color')
    # ### end Alembic commands ###

    delete_colors()


def insert_colors():
    color_table = table(
        'color',
        column('id', sa.Integer),
        column('name', sa.String),
        column('shortcut', sa.String),
        column('hex_code', sa.String),
    )

    op.bulk_insert(color_table, [
        {
            'id': 1,
            'name': 'Белый',
            'shortcut': 'W',
            'hex_code': '#fbff80',
        },
        {
            'id': 2,
            'name': 'Зеленый',
            'shortcut': 'G',
            'hex_code': '#78b33b',
        },
        {
            'id': 3,
            'name': 'Красный',
            'shortcut': 'R',
            'hex_code': '#df5837',
        },
        {
            'id': 4,
            'name': 'Синий',
            'shortcut': 'U',
            'hex_code': '#6e98c4',
        },
        {
            'id': 5,
            'name': 'Черный',
            'shortcut': 'B',
            'hex_code': '#2e2c2b',
        },
        {
            'id': 6,
            'name': 'Бесцветный',
            'shortcut': 'Z',
            'hex_code': '#c1c1c1',
        }
    ])


def delete_colors():
    op.execute('DELETE FROM colors')
