from .application_view import *
from .color_view import *
from .config_view import *
from .passive_bonus_to_school_view import *
from .passive_bonus_view import *
from .school_view import *
from .spell_to_color_view import *
from .spell_to_school_view import *
from .spell_view import *
from .uploaded_file_view import *
from .user_view import *
