version: '3.7'


x-db-env-variables: &db-env-variables
  TK_DB_USERNAME: 'postgres'
  TK_DB_PASSWORD: 'my_secret_password'
  TK_DB_PORT: 5432


x-api-env-variables: &api-env-variables
  TK_DB_HOST: 'tarkir-db'


services:

  tarkir-db:
    image: library/postgres:13
    container_name: tarkir-db
    ports:
      - 5444:5432
    env_file:
      - .env
    volumes:
      - ../postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: api
    ports:
    - 5000:5000
    depends_on:
      - tarkir-db
    env_file:
      - .env
    volumes:
      - .:/tarkir-tools
      - ../tarkir-upload/:/tmp/tarkir-upload
