version: '3.7'

services:

  tarkir-db:
    image: library/postgres:13
    container_name: tarkir-db
    ports:
      - 5444:5432
    env_file:
      - .env
    volumes:
      - ../postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: api
    ports:
    - 5000:5000
    depends_on:
      - tarkir-db
    env_file:
      - .env
    volumes:
      - .:/tarkir-tools
      - ../tarkir-upload/:/tmp/tarkir-upload
